### ISSUE TITLE
Flyway DB migration basic tutorial

### ISSUE THREAD

**Issue by MakMuftic** [KSET/api-jobfair-fer-unizg-hr#2]
https://blog.codecentric.de/en/2017/01/flyway-tutorial-managing-database-migrations/

**Comment by mpetrunic** [comment]
Ovo je bitno:
http://www.jeremyjarrell.com/using-flyway-db-with-distributed-version-control/

Ima unutra link na task koji se može postaviti u gradleu da stvara migracije prefixirane sa timestampom

**Comment by labramusic** [comment]
Ovaj task na linku https://gist.github.com/jeremyjarrell/6083207 nije bas to sto nam treba a pseudokod mi isto ne pomaze bas. Mislim da je bolje da ovo napravi netko tko je vec radio tako nesto, da zavrsimo s konfiguracijom sto prije da mozemo poceti kodirati.
Pushao sam na branch 'flyway' konfiguraciju, ispricavam se ako sam se branchao s krivog brancha.

**Comment by mpetrunic** [comment]
Stavio sam ti komentar na kod. Budem ja nabrzaka napisao ovaj groovy task :)
